//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlotterSBP_Sheduler
    {
        public int SID { get; set; }
        public Nullable<bool> RegTimerStatus { get; set; }
        public string RegStartTime { get; set; }
        public string RegEndTime { get; set; }
        public string RegFreq { get; set; }
        public Nullable<bool> RegIsUpdated { get; set; }
        public Nullable<bool> RegIsRun { get; set; }
        public Nullable<bool> FwdTimerStatus { get; set; }
        public string FwdStartTime { get; set; }
        public string FwdEndTime { get; set; }
        public string FwdFreq { get; set; }
        public Nullable<bool> FwdIsUpdated { get; set; }
        public Nullable<bool> FwdIsRun { get; set; }
    }
}
