//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class fx_maturity_profile
    {
        public string br { get; set; }
        public string dealno { get; set; }
        public string seq { get; set; }
        public Nullable<System.DateTime> dealdate { get; set; }
        public Nullable<System.DateTime> vdate { get; set; }
        public string ps { get; set; }
        public string ccy { get; set; }
        public string swapdeal { get; set; }
        public Nullable<decimal> ccyamt { get; set; }
        public Nullable<decimal> pkramt { get; set; }
        public Nullable<decimal> ccyrate_8 { get; set; }
        public string acct { get; set; }
        public string sn { get; set; }
        public string prodcode { get; set; }
        public string prodtype { get; set; }
        public string brok { get; set; }
        public string means { get; set; }
        public string cost { get; set; }
        public string port { get; set; }
        public string brok_desc { get; set; }
        public string nostro { get; set; }
        public string nostro_desc { get; set; }
    }
}
