//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class fxacuphbl1
    {
        public Nullable<int> postdate { get; set; }
        public string Period { get; set; }
        public string CCY { get; set; }
        public Nullable<decimal> AmountCR { get; set; }
        public Nullable<decimal> AmountDR { get; set; }
        public Nullable<decimal> Net { get; set; }
    }
}
