//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OW_USERS
    {
        public int USER_ID { get; set; }
        public string EMP_NO { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string FULL_NAME { get; set; }
        public string EMAIL_ID { get; set; }
        public string AUTH_LEVEL { get; set; }
        public string REGION_CODE { get; set; }
        public string USER_TYPE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_TIME { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_TIME { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<bool> IS_ADMIN { get; set; }
    }
}
