//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBP_BlotterSessionDetails
    {
        public long ID { get; set; }
        public string SessionID { get; set; }
        public int UserID { get; set; }
        public string IP { get; set; }
        public string Status { get; set; }
        public string URL { get; set; }
        public string Activity { get; set; }
        public Nullable<System.DateTime> ActivityTime { get; set; }
        public string Data { get; set; }
        public Nullable<System.DateTime> SessionStart { get; set; }
        public Nullable<System.DateTime> SessionEnd { get; set; }
        public Nullable<bool> LoginStatus { get; set; }
        public string LoginGUID { get; set; }
    
        public virtual SBP_LoginInfo SBP_LoginInfo { get; set; }
    }
}
