//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBP_BlotterDLDT
    {
        public long Sno { get; set; }
        public string DataType { get; set; }
        public string DealType { get; set; }
        public Nullable<long> DealNo { get; set; }
        public Nullable<System.DateTime> VDate { get; set; }
        public Nullable<System.DateTime> MDate { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Inflow { get; set; }
        public Nullable<decimal> Outflow { get; set; }
        public Nullable<bool> Recon { get; set; }
        public Nullable<bool> Rev { get; set; }
        public Nullable<int> BR { get; set; }
        public Nullable<int> CurId { get; set; }
        public string NostroCode { get; set; }
    }
}
