//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBP_BlotterRTGS1
    {
        public int Sno { get; set; }
        public Nullable<System.DateTime> TXN_DTE_TME { get; set; }
        public string ACCT_Description { get; set; }
        public decimal Inflow { get; set; }
        public decimal Outflow { get; set; }
        public int BatchCount { get; set; }
        public string Br { get; set; }
    }
}
